# Generated by Django 3.2.4 on 2021-06-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='delay',
            new_name='status',
        ),
    ]
